# GitHub Pages configuration for CLDP anonymous submission
title: "Closed-Loop Diffusion Planning over Multi-Modal Distribution"
description: "Anonymous submission for academic review"
url: ""
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Exclude files from processing
exclude:
  - README.md
  - .git/
  - .gitignore

# Navigation
header_pages:
  - index.html

# Anonymous submission settings
author: "Anonymous"
email: ""
show_excerpts: false